version: 'latest'
services:
  postgres:
    container_name: webapp
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webapp
    ports:
      - "5432:5432"
    restart: always